### ISSUE TITLE
[godot 4] Spine version of the editor has broken fundamental script class functionality

### ISSUE THREAD

**Issue by karljs** [EsotericSoftware/spine-runtimes#2243]
I know the Godot 4 version is unstable, and I hope reports about it are useful.  Godot 4 recently changed how they store information about script classes, i.e. using `class_name MyClass` at the top of a GDScript file.  Previously this was stored in the `project.godot` file, but it's now stored in `.godot/global_script_class_cache.cfg` and is intended to be easy to generate.  Some part of those changes seem to be broken in the version of the editor built with the Spine module.

If I open any version of vanilla Godot, create a new scene/script and add a `class_name` statement at the top, it's immediately added to `.godot/global_script_class_cache.cfg`.  If I then open the version of Godot with the Spine module and do the same steps, that file remains effectively empty.

I don't know if this is a bug in the module somehow, or an issue in Godot with any plugins, but I figured this is probably a good place to start.

**Comment by badlogic** [comment]
Do you know how recent that change is? The GH Action building "our" 4.0 editor build last succeeded 2 weeks ago.

We do not touch anything in Godot itself, we merely link our own module into it. So the only explanation I have is that this change was commited to Godot's master in the last 2 weeks, after our last 4.0 build succeeded. If that's the case, you can compile the editor locally.

Godot 4.0 currently lacks batching of polygons and meshes. I do not recommend using it with Spine until that's resolved on their end (for which there's no ETA afaik).

**Comment by badlogic** [comment]
Think I fixed up the GH action, build is currently running. See https://github.com/EsotericSoftware/spine-runtimes/actions/runs/4148007194

If that succeeds, then the new 4.0 binary of ours should fix the issue if the change as made in the last 2 weeks in Godot master. https://spine-godot.s3.eu-central-1.amazonaws.com/4.1/master/godot-editor-windows.zip

**Comment by karljs** [comment]
Thanks for the information and getting the Action fixed.  Unfortunately it's not a matter of missing some commits (I was grabbing the binaries from the Actions directly) and the most recent version still shows this problem.

That said, in retrospect this is almost certainly is a bug in Godot itself and not the runtime.  I'll report this there and consider this closed for the time being.

**Comment by badlogic** [comment]
I wouldn't be 100% sure it's a bug in Godot, since their vanilla binaries
work as intended.

**Comment by karljs** [comment]
The Godot devs certainly agree 😆  I guess my feeling was that even if the Spine modules were producing an error, that shouldn't be allowed to prevent core editor functionality from working, but that may be asking too much (in the world of C++ anyway).  Reopening for now.

**Comment by badlogic** [comment]
Found the issue. We have a bunch of custom resource types (atlas, skeleton files). Their `get_resource_type()` implementation was incorrect and would return e.g. `SpineAtlasResource` for any file in the Godot project, including scripts. Because of this, the class cache mechanism didn't trigger.

Fixed in the 4.1 and 4.2-beta branches. New binaries are building via GitHub actions. Thanks for reporting!
